### ISSUE TITLE
如何“糊”出一个Web IDE?

### ISSUE THREAD

**Issue by zhouzhongyuan** [zhouzhongyuan/qa#83]
- 照着[VSCode Online](https://zhouzhongyuan.visualstudio.com/_git/demo?path=%2Findex.js&version=GBmaster&_a=contents)的样子做。
- 部分交互照着[Coding ](https://coding.net/)做

## TODO

- [x] tty [xterm.js](https://github.com/sourcelair/xterm.js)
- [x] File Explorer [react-treeview](https://github.com/chenglou/react-treeview)
- [x] Editor [react-monaco-editor](https://github.com/superRaytin/react-monaco-editor), [monaco-editor](https://github.com/Microsoft/monaco-editor)
- [x] [git server](https://github.com/zhouzhongyuan/qa/issues/83#issuecomment-318975870)

- [x] 监控文件[chokidar](https://github.com/paulmillr/chokidar)

**Comment by zhouzhongyuan** [comment]
.

**Comment by zhouzhongyuan** [comment]
- [要实现一个Web IDE 需要哪些前端技术？ - 知乎](https://www.zhihu.com/question/41050429)

- [如何评价 Visual Studio Code？ - 知乎](https://www.zhihu.com/question/29984607)

- [CodeMirror - In-browser code editor](https://github.com/codemirror/CodeMirror)

- [Monaco Editor](https://microsoft.github.io/monaco-editor/)
- [Xterm.js](https://xtermjs.org/)

**Comment by zhouzhongyuan** [comment]
## 名词
中文 |  英文
--  | ---
文件树 | Files Explorer(~~不是File Tree~~)

**Comment by zhouzhongyuan** [comment]
# GitLab Community Edition
1. Install
[GitLab Community Edition](https://gitlab.com/gitlab-org/gitlab-ce)
[Install Gitlab CE](https://about.gitlab.com/installation/#ubuntu)

[Maintenance commands](https://docs.gitlab.com/omnibus/maintenance/README.html)

[GitLab Architecture Overview - GitLab Documentation](https://docs.gitlab.com/ce/development/architecture.html)

[Production Architecture | GitLab](https://about.gitlab.com/handbook/infrastructure/production-architecture/#infra-archi-diagram)

[Omnibus GitLab documentation - GitLab Documentation](https://docs.gitlab.com/omnibus/README.html)

[Configuration options - GitLab Documentation](https://docs.gitlab.com/omnibus/settings/configuration.html)


2. Configuring the external URL for GitLab 
[Configuration options - GitLab Documentation](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab)，否则，无法创建新用户。

**Comment by zhouzhongyuan** [comment]
# coding是如何做的
架构师：杜万
- [Docker 在 Coding WebIDE 项目中的运用 - Coding 博客](https://blog.coding.net/blog/Docker-use-in-Coding-WebIDE)
- [技术相关的博客 - Coding 博客](https://blog.coding.net/technology/blogs?page=2)
- [Coding WebIDE 前端架构变迁 - Coding 博客](https://blog.coding.net/blog/the-evolution-of-coding-webide-frontend-architecture)
- [Coding/WebIDE: Coding WebIDE Community Edition](https://github.com/Coding/WebIDE)
- [要实现一个Web IDE 需要哪些前端技术？ - 知乎](https://www.zhihu.com/question/41050429/answer/122380612)

**Comment by zhouzhongyuan** [comment]
https://www.lucidchart.com/documents/edit/309f4cc9-fdbf-47bf-940f-b1fa9954071c

**Comment by zhouzhongyuan** [comment]
# 别人家的web ide

[coding - WebIDE](https://ide.coding.net/ws/jqmghr)
[Root - Editor](https://orionhub.org/edit/edit.html#/workspace/zhouzhongyuan-OrionContent)
[Particle Login](https://login.particle.io/signup?app=web-ide&redirect=https://build.particle.io/build)

# 别人家的项目管理
[ANTD ADMIN](http://47.92.30.98:8000/chart/lineChart)

**Comment by zhouzhongyuan** [comment]
# 如何设计Store?
## 别人如何设计的
- [admin-on-rest-demo](https://marmelab.com/admin-on-rest-demo)
[data](https://marmelab.com/admin-on-rest-demo/data.js)一次传输完毕
111B,300ms,总计2000条数据
